include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: error
    invalid_use_of_protected_member: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    # Disabled until we have proper documentation
    public_member_api_docs: false

    # Enforce modern Dart patterns
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_dynamic_calls: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
